name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -  
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Create env file
      run: |
        touch .env
        echo "DEBUG=False" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "MONGO_LINK=${{ secrets.MONGO_LINK }}" >> .env
        echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
        echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
        echo "SUPER_USER=${{ secrets.SUPER_USER }}" >> .env
        echo "ADMIN_USER=${{ secrets.ADMIN_USER }}" >> .env
        echo "WORKER_USER=${{ secrets.WORKER_USER }}" >> .env
        echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
        echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
        echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
        echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
    -
      name: Build the Docker image
      run: |
        docker build --file Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker:latest .
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker:latest
    -
      name: Delete env file
      run: |
        rm -rf .env
    -
      name: Deploy on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          sudo docker kill $(sudo docker ps -q)
          sudo docker rm $(sudo docker ps -a -q)
          sudo docker rmi $(sudo docker images -q)
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker:latest
          sudo docker run -d -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker