name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    enviroment: env
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -  
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Create env file
      run: |
        touch .env
        echo SECRET_KEY=$SECRET_KEY >> .env
        echo MONGO_LINK=$MONGO_LINK >> .env
        echo MONGO_USERNAME=$MONGO_USERNAME >> .env
        echo MONGO_PASSWORD=$MONGO_PASSWORD >> .env
        echo DATABASE_NAME=$DATABASE_NAME >> .env
        echo SUPER_USER=$SUPER_USER >> .env
        echo ADMIN_USER=$ADMIN_USER >> .env
        echo WORKER_USER=$WORKER_USER >> .env
    -
      name: Build the Docker image
      run: |
        docker build --file Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker:latest .
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker:latest
    -
      name: Deploy on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker:latest
          sudo docker run -d -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/gmtv-docker
    -
      name: Delete env file
      run: |
        rm -rf .env